CUDA_VISIBLE_DEVICES=0 python demo.py \
--coco_path 'data/coco' \
--output_dir logs/visualize \
--batch_size 2 \
--epochs 35 \
--lr_drop 35 \
--backbone clip_RN50 \
--text_len 15 \
--ovd \
--region_prompt_path logs/region_prompt_R50.pth \
--save_every_epoch 50 \
--dim_feedforward 1024 \
--use_nms \
--num_queries 1000 \
--anchor_pre_matching \
--remove_misclassified \
--condition_on_text \
--enc_layers 3 \
--text_dim 1024 \
--condition_bottleneck 128 \
--split_class_p 0.2 \
--model_ema \
--model_ema_decay 0.99996 \
--save_best \
--label_version small_drop \
--disable_init \
--target_class_factor 8 \
--resume logs/COCO/small_drop/RN50/checkpoint_best.pth